### ISSUE TITLE
UI shows 404 page when following link or refreshing page

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1140] opened 2024-03-28 09:24 UTC
e.g. the following path exists but the link doesn't work

https://arequipa.sia.tech/buckets/default/files

**Comment by alexfreska** [comment] 2024-03-28 11:36
This is a dupe of https://github.com/SiaFoundation/renterd/issues/1026 and is fixed by https://github.com/SiaFoundation/web/pull/537. It is in the next release: https://github.com/SiaFoundation/web/pull/531.

**Closed** 2024-03-28 12:57 UTC
Labels: bug
