### ISSUE TITLE
Debug high number of offline hosts

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#1060] opened 2024-03-14 08:48 UTC
Even after all the improvements we made it seems like nodes (especially Arequipa) are suffering from a lot of churn due to offline hosts. We should get to the bottom of what's causing this.

**Comment by peterjan** [comment] 2024-04-18 08:00
This is marked as `high` priority but I'm not sure if it's still all that relevant? The hosts that are marked offline now are shown offline in siastats as well and don't respond to pings.

**Comment by ChrisSchinnerl** [comment] 2024-04-18 08:02
Yeah just keeping this open as a reminder for a little while longer until we are confident that there is actually no issue anymore.

**Comment by peterjan** [comment] 2024-07-18 11:56
Small update on this one: it appears churn caused by hosts going offline has dropped drastically. At the time of writing there's only two hosts on `arequipa` that churned because they were offline. One got removed 4h ago and the other 24h ago, both hosts are still offline. There is however one host (spsc.duckdns.org) that is flip-flopping in and out of the set. Since it's duckdns though this particular case would likely be resolved by https://github.com/SiaFoundation/renterd/issues/1375.

**Closed** 2024-08-26 11:17 UTC
