### ISSUE TITLE
Migrations running with no objects present

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#772] opened 2023-11-29 10:14 UTC
## Describe the bug
The autopilot started slab migrations, even though there are no objects in the bus.

## Expected behaviour
Nothing should be migrated. Or, all associated slabs should be deleted upon the object deletion.

## Additional context
```
curl -u "":<PASSWORD> -X GET http://localhost:9980/api/bus/buckets
[
	{
		"createdAt": "2023-09-06T15:20:41.994443001Z",
		"name": "default",
		"policy": {
			"publicReadAccess": false
		}
	}
]

curl -u "":<PASSWORD> -X POST http://localhost:9980/api/bus/objects/list -d '{"bucket":"default"}'
{
	"hasMore": false,
	"nextMarker": "",
	"objects": null
}
```
![image](https://github.com/SiaFoundation/renterd/assets/72828450/49d065a7-0402-4153-8047-7146edfafa0e)

### General Information
Are you running a fork of `renterd`? No
Are you on the mainnet or on the testnet? Mainnet

### Renterd Logs
{"level":"info","date":"2023-11-29T10:59:14+01:00","component":"autopilot.migrator","msg":"performing migrations"}
{"level":"debug","date":"2023-11-29T10:59:14+01:00","component":"autopilot.migrator","msg":"recomputed slab health in 450.318µs"}
{"level":"debug","date":"2023-11-29T10:59:14+01:00","component":"autopilot.migrator","msg":"36 potential slabs fetched for migration"}
{"level":"debug","date":"2023-11-29T10:59:14+01:00","component":"autopilot.migrator","msg":"36 slabs to migrate"}
{"level":"info","date":"2023-11-29T10:59:23+01:00","component":"autopilot.migrator","msg":"worker: migration 1/36 succeeded, key: key:53a51084802224e43db38fb17e23c8915268a249c9d80a903d1db7b08f4e533c, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T10:59:38+01:00","component":"autopilot.migrator","msg":"worker: migration 2/36 succeeded, key: key:1be6d5b4f6fffd15624c19c6950e9f65b1ae9f7e66512052ac105c99e1ffc176, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T10:59:57+01:00","component":"autopilot.migrator","msg":"worker: migration 3/36 succeeded, key: key:0265a9b0971d1712f9005c5ac62afaec1c306a85ec8167c380dc9398d24839aa, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:00:06+01:00","component":"autopilot.migrator","msg":"worker: migration 4/36 succeeded, key: key:e92bd53815de59213e48de61bb9968b204c815046b0d550a17b7ca4c46ab9552, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:00:14+01:00","component":"autopilot.migrator","msg":"worker: migration 5/36 succeeded, key: key:aaf81dc4e95fee8e7653e59d623dc8b0036b700cedc49e6becb2238b6ef85bc8, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:00:20+01:00","component":"autopilot.migrator","msg":"worker: migration 6/36 succeeded, key: key:1cc9ab85dd84d66fd82460e2aa7260ccaf4ab1d00fbd345e532775c648fe54b2, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:00:33+01:00","component":"autopilot.migrator","msg":"worker: migration 7/36 succeeded, key: key:f8f10b43c72bcc15b59955094ca0abcf938378907f458affb0bac104b91dd6a1, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:00:38+01:00","component":"autopilot.migrator","msg":"worker: migration 8/36 succeeded, key: key:73b52265740e8a0076e51ae5ad42cb9303d9aa751d191782693f675a31e6b695, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:00:44+01:00","component":"autopilot.migrator","msg":"worker: migration 9/36 succeeded, key: key:baab272f7840241c531d57ff79a931dc6f0c3e83e3703030f8e89e9d97ff4f9f, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:00:50+01:00","component":"autopilot.migrator","msg":"worker: migration 10/36 succeeded, key: key:8cf2eb30276c978e588edc1252079e88a7a7eb9f9c2fff646633819238a5bb3f, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:01:00+01:00","component":"autopilot.migrator","msg":"worker: migration 11/36 succeeded, key: key:75569f83f47c70ee28041eba5663794ba2dedbc20242b866f15c06927ee3aa97, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:01:05+01:00","component":"autopilot.migrator","msg":"worker: migration 12/36 succeeded, key: key:5d36eb02aab590a2f193e1c203801ed3370a32cc988576b43981cae0063d953b, health: 0.5, overpaid: false, shards migrated: 3"}
{"level":"info","date":"2023-11-29T11:01:18+01:00","component":"autopilot.migrator","msg":"worker: migration 13/36 succeeded, key: key:2d0827bb3ce4404bd47060e048d0a91c5ba44a3b00996be0d00285c1f98968dc, health: 0.5, overpaid: false, shards migrated: 3"}

**Comment by ChrisSchinnerl** [comment] 2023-11-29 17:07
Can you check whether those slabs belong to multipart uploads? Even without objects there are some conditions where a slab is not pruned.

**Comment by ChrisSchinnerl** [comment] 2023-11-30 09:21
The `slices` table has a `db_multipart_id` foreign key which references multipart upload parts.

**Comment by mike76-dev** [comment] 2023-11-30 10:46
Found the foreign key `db_multipart_part_id`, and yes, there's 61 row in `slices` with non-empty part IDs.

**Comment by mike76-dev** [comment] 2023-11-30 15:55
Okay, but then there needs to be a user-friendly way to delete them, or the users will be paying forever for migrating air molecules.

**Comment by ChrisSchinnerl** [comment] 2023-12-01 13:23
Closing this issue since it's not unexpected behaviour. Following up here in https://github.com/SiaFoundation/web/issues/429

**Closed by ChrisSchinnerl** 2023-12-01 13:23 UTC
