### ISSUE TITLE
Upload packing breaks rclone integration (api returns file size 0 for files waiting to be uploaded into network?)

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#544] opened 2023-08-11 11:20 UTC
## Describe the bug

After enabling upload packing rclone integration in @redsolver rclone fork is broken. Probably api is returning file size 0 for non-fully uploaded files (those that are waiting to be packed)

```
2023-08-11 13:14:55 ERROR : file.txt: corrupted on transfer: sizes differ 129 vs 0
2023-08-11 13:14:55 INFO  file.txt: Removing failed copy
```

## Expected behaviour
Api should report correct file size regardless of it is uploaded to the network or not.

### General Information
Latest renterd on zen.

### Renterd Config
Please provide us the following information:

**Autopilot Config**

```bash
{
        "contracts": {
                "set": "autopilot",
                "amount": 50,
                "allowance": "5000000000000000000000000000",
                "period": 6048,
                "renewWindow": 2016,
                "download": 10000000000000,
                "upload": 10000000000000,
                "storage": 10000000000000
        },
        "hosts": {
                "allowRedundantIPs": false,
                "maxDowntimeHours": 1440,
                "scoreOverrides": null
        },
        "wallet": {
                "defragThreshold": 1000
        }
}
```

**Bus Config**

```bash
{
        "minShards": 2,
        "totalShards": 6
}

{
        "hostBlockHeightLeeway": 6,
        "maxContractPrice": "15000000000000000000000000",
        "maxDownloadPrice": "3000000000000000000000000000",
        "maxRPCPrice": "1000000000000000000000",
        "maxStoragePrice": "631593542901",
        "maxUploadPrice": "3000000000000000000000000000",
        "minAccountExpiry": 86400000000000,
        "minMaxCollateral": "10000000000000000000000000",
        "minMaxEphemeralAccountBalance": "1000000000000000000000000",
        "minPriceTableValidity": 300000000000
}
```

**Contract Set Contracts**

```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4995    0  4995    0     0  2138k      0 --:--:-- --:--:-- --:--:-- 2438k
7
```

### Renterd Logs
I haven't seen anything.

**Comment by ChrisSchinnerl** [comment] 2023-08-11 12:05
Do you happen to have a way to reproduce this issue that doesn't involve rclone? I've tried uploading a 129 byte test file and used two different ways of fetching its size from the bus. Both were successful.

```
curl -u ":asdf" unraid.local:9980/api/bus/objects/tiny.txt      
{
	"object": {
		"name": "/tiny.txt",
		"size": 129,
		"health": 1,
		"key": "key:4df6f4c15fd75088be21dc09a8d079965f960e58b380fc0e55379c94bee3ad21",
		"slabs": [],
		"partial_slab": {
			"minShards": 10,
			"totalShards": 30,
			"data": "DAUUCy5ADPKtMdrX887HIlh3vdpOz1sSolnKUvsrE68u3sgCLM71NHRljG1Rdx18Khrtx2TtMl73cCG5SDEmzX4sxZU3wJAA0SgP6r3fKy+FkgU2wRKJy5Cd1/w+31jc5q5eBPoXBn/XzhmkJBNgrPMi8w/mDyydoyQohIG9cgty"
		}
	}
}
curl -u ":asdf" unraid.local:9980/api/bus/objects/        
{
	"entries": [
		{
			"name": "/tiny.txt",
			"size": 129,
			"health": 1
		}
	]
}
```

**Comment by artur9010** [comment] 2023-08-11 12:11
Uploads from webui are fine, it returns empty list of slabs - rclone uses those slabs to get file size - https://github.com/rclone/rclone/pull/6988/files

```
{
        "object": {
                "name": "/location.svg",
                "size": 303,
                "health": 1,
                "key": "key:cd26199230c524e1576a2aeccd1c081322214851e87bed5ae88a2bbad53eca7a",
                "slabs": [],
                "partial_slab": {
                        "minShards": 2,
                        "totalShards": 6,
                        "data": "SFIxEc6JT7XMsSPzrnrMUWfMIoNIV5+bRcO3PdxJP9pwofmbZj3uDs++C+OkBNO3eF3jHJW4PDT0XYP2vWpHObGsVI0gC0nVTx9RDeZbfGGf+/Ipu3/+2bgInt39J+phu3VJN8PbcL5YDAtKV10dPVc+AtGk4Hf6BxpuI/PwSJ3weY7dzIWkMKwcbjisPMnT2w49XB/IRyBpr3HbT74KGTcy6RVwgvCbOOpUXjHMJMApzgJpcjia4smK/QPlkvyK181n6/+rAmx3abnyq9d8R9mpvZtWfz/C7PJhaDnx8E34D2G9pRtbgUBSqwOZPED9TXi7fpZaHihnmYr8XCAa/Myj0oRn3oBNA0BNlzPTiyt/8rSaUNpnoUvEqtDvs/VFnXv1U0/8IWi7sry0quJH"
                }
        }
}
```

**Comment by ChrisSchinnerl** [comment] 2023-08-11 12:16
Ok to fix this `rclone` needs to check the `partialSlab` field of the response as well. It's the raw data that hasn't been uploaded yet. (NOTE: `partial_slab` was updated to `partialSlab` for consistency)

Closing this since there is no more action to be taken in `renterd`.

**Closed by ChrisSchinnerl** 2023-08-11 12:16 UTC

**Comment by multikatt** [comment] 2023-08-14 19:39
I have attempted to fix this myself here: https://github.com/multikatt/rclone/tree/sia (which also supports renaming/moving files).
The way it previously worked to check that files had been uploaded correctly was looping through all the slabs, adding up the lengths of those objects. partialSlabs doesn't contain lengths though, so i've changed it to use object.size directly.
It seems to work fine, but im surprised this was done the loop-way before, so this might not be a good solution for some reason. In which case I guess we would need a length field on the partialSlabs as well.
