### ISSUE TITLE
Sia renterd overrided old consensus folder

### ISSUE THREAD

**Issue by cmdntd** [SiaFoundation/renterd#1515] opened 2024-09-09 07:14 UTC
### Current Behavior

I tried to save consensus folder to load renterd faster with backups.
But it overrided old consensus folder, and loads from beginning.

### Expected Behavior

How could renterd read old consesus folder to make it faster at beginning?

### Steps to Reproduce

1. Old consensus, data, slab
2. Run sia from docker with volume to old folder
3. It deletes old files, and loads from beginning

### Version

1ed897e

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

docker:master

### Autopilot Config

{ 	"contracts": { 		"set": "autopilot", 		"amount": 50, 		"allowance": "3808000000000000000000000000", 		"period": 6048, 		"renewWindow": 2016, 		"download": 1400000000000, 		"upload": 1400000000000, 		"storage": 2000000000000, 		"prune": false 	}, 	"hosts": { 		"allowRedundantIPs": false, 		"maxDowntimeHours": 336, 		"minProtocolVersion": "1.6.0", 		"minRecentScanFailures": 10, 		"scoreOverrides": null 	} }

### Bus Config

{"default":"autopilot"} {"hostBlockHeightLeeway":6,"maxContractPrice":"1000000000000000000000000","maxDownloadPrice":"800000000000000000000000000","maxRPCPrice":"1000000000000000000000","maxStoragePrice":"64814814815","maxUploadPrice":"40000000000000000000000000","migrationSurchargeMultiplier":10,"minAccountExpiry":86400000000000,"minMaxCollateral":"10000000000000000000000000","minMaxEphemeralAccountBalance":"1000000000000000000000000","minPriceTableValidity":300000000000} {"minShards":10,"totalShards":30} {"enabled":true,"slabBufferMaxSizeSoft":4294967296}

### Contract Set Contracts

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                  Dload  Upload   Total   Spent    Left  Speed 100 41316    0 41316    0     0  5935k      0 --:--:-- --:--:-- --:--:-- 6724k 50

### Anything else?

I remember it not to delete old consensus at former versions.

**Comment by cmdntd** [comment] 2024-09-09 10:39
When did it switch to? That means I could save new consensus for future, doesn't it?

**Comment by ChrisSchinnerl** [comment] 2024-09-09 11:38
Closing this since it's expected behavior starting from `v1.1.0`. 

@cmdntd yes, you can save the new consensus now like you did the old one.

**Closed by ChrisSchinnerl** 2024-09-09 11:38 UTC
Labels: bug
