### ISSUE TITLE
UI: Contract Set Contracts Filter

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#454] opened 2023-06-29 04:30 UTC
The contracts page should have a filter, or just by default show only the contracts that are truly active, which IIRC is the equiv to `/api/bus/contracts/set/autopilot`

**Comment by peterjan** [comment] 2023-08-11 09:27
I think the contracts page should indeed have an option to filter on contract set contracts, or have some indication on what contracts belong the configured contract set. I took the liberty of updating the issue title a bit to reflect this.

**Comment by peterjan** [comment] 2023-12-14 09:23
duplicate of https://github.com/SiaFoundation/renterd/issues/716

**Closed by peterjan** 2023-12-14 09:23 UTC
Labels: ui
